alert("     CAPTACION DE SOCIOS \nDEL CLUB 'ORIENTE PETROLERO'")
let nombre= ""
nombre = prompt("INGRESE SU NOMBRE POR FAVOR")
alert("BIENVENIDO "+(nombre) +"POR FAVOR SELECCIONA LAS OPCIONES CORRECTAMENTE")